app:
  name:        gin-exercises
  serve_type:  https
  debug:       false

database:
  driver:
  host:
  port:
  user:
  password:
  dbname:
  charset:

redis:
  host:
  port:
  password:
  db:

aes:
  key:        dGhpc2lzMzJiaXRsb25ncGFzc3BocmFzZWltdXNpbmc=
